scavenger_points = {
    "type": "FeatureCollection",
    "name": "puntos_actualizados",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
    { "type": "Feature", "properties": { "name": "Tūranga", "points": "+10", "challenge": "Find the portrait of Margaret Mahy and take a picture of a teammate standing beside it.", "information": "Tūranga, the city's central library, opened in 2018. The construction included guidance from Ngāi Tahu and the Ngāi Tūāhuriri rūnanga, as well as state-of-the-art earthquake strengthening with post-tensioned walls and viscous dampers.", "note": null, "bonus": "Bonus +5 Include a teammate holding a book by Marget Mahy in the picture.", "points_int": 10, "bonus_int_1": 5 }, "geometry": { "type": "Point", "coordinates": [ 172.63711, -43.52995, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Justice Precinct", "points": "+10", "challenge": "How many different colours are the feathers on the justice precinct?", "information": "A group of buildings encompassing the Justice Building, the Emergency Services Building, and the Christchurch Central Police Station. The part of the design features a motif of a kākāpō feather cloak.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.63508, -43.53418, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Earthquake Memorial (Official)", "points": "+10", "challenge": "What does \"Kia atawhai ki te iwi\" mean, and who said it?", "information": "The official memorial for the February 22nd earthquakes, consisting of a plaque inscribed with each name of the victims, both in English and, in some cases, in a native script.", "note": null, "bonus": null, "points_int": 10, "bonus_int_1": null, "bonus_int_2": null }, "geometry": { "type": "Point", "coordinates": [ 172.63158, -43.53468, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Margaret Mahy Playground", "points": "+10 plus bonus points (see below).", "challenge": "Take a picture of a teammate going down one of the slides.", "information": "The city's largest playground, loved by kids and kids-at-heart alike. Named after the famous New Zealand children's writer, the playground alone cost over three million dollars.", "note": null, "bonus": "Wide slide +3, swirly slide +5.", "points_int": 10, "bonus_int_1": 5, "bonus_int_2": 3 }, "geometry": { "type": "Point", "coordinates": [ 172.64077, -43.52832, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Te Oranga Ra", "points": "+10", "challenge": "Find the final virtue.", "information": "Formerly one of the six Places of Tranquility parks around Christchurch, this garden is dedicated to promoting good mental health and working against gambling and substance addiction.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.64008, -43.52734, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Cardboard Cathedral", "points": "+10", "challenge": "To what percentage of the New Zealand Building Code is the cardboard cathedral built?", "information": "The Transitional Cathedral, sometimes referred to as the 'Cardboard Cathedral', is a temporary replacement for the damaged Christchurch Cathedral. Built by architect Shigeru Ban, the structure uses earthquake-resilient materials such as wood and cardboard.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.64306, -43.53236, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Christchurch Cathedral", "points": "+10", "challenge": "How many of the cathedral’s original thirteen bells have been restored?", "information": "The site of the Christchurch Cathedral. Public opinion was divided around demolishing or repairing this location, having served as a centre-point for locals and tourists in the past. Repairs began in 2019, with the Cardboard Cathedral having been constructed as a 'transitional cathedral'.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.63687, -43.5309, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Super Street Arcade", "points": "+10 plus bonus points (see below).", "challenge": "Get points based on your comparative ranking in space invaders. The team with highest score gets an extra +5 points, second highest gets +3 points, third highest gets +2.", "information": "As a giant controller and a five metre-wide screen, this site continues as one of the surviving gap filler projects, the aim being to bring fun and life back into the central city. The games that have been featured on there are made by New Zealand developers.", "note": "If this is not working for some reason, take a photo and add +3 points.", "bonus": null, "points_int": 10, "bonus_int_1": null, "broken": 3 }, "geometry": { "type": "Point", "coordinates": [ 172.6414, -43.5353, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Rauora Park (Hammock Forest)", "points": "+10", "challenge": "Take a photo of at least one team member in a hammock.", "information": "Designed by Gap Filler, the hammock forest was built to bring more life and relaxation into the city. The use of logs was specifically chosen to evoke the calming effect of being in nature.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.64009, -43.53149, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Arts Centre", "points": "+10", "challenge": "Go to the UC arts building. Can you take a photo of some retrofitted earthquake bracing on the outside of the building?", "information": "Created as a centre for artists and their crafts, the Arts Centre serves as an example of not only historical, cultural, and architectural heritage of the region. Many of the centre’s buildings are on the heritage buildings list and have undergone a $250 million restrengthening project.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.62818, -43.53146, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Hine Pāka (Bus Interchange)", "points": "+10", "challenge": "Take a photo of the constellations on the bus interchange roof and name the two constellations used to identify south.", "information": "Named after a traditional fowling tree that resided in the same spot, this area was once used by Ngāi Tūāhuriri as an important hunting area for local birds. Constellation patterns are displayed on the ceiling, referencing back to the traditional navigation practices that exist in Te Ao Māori. ", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.63713, -43.5344, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "The Commons", "points": "+10", "challenge": "How many volunteers helped to construct the Pallet Pavilion?", "information": "Home to the offices of Gap Filler and Life in Vacant Spaces, the commons is a community-run space that hosted cafés, an outdoor cinema, arts performances, and a natural area for the community to meet.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.63391, -43.52692, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Christchurch Swing", "points": "+10", "challenge": "Take a picture of a team member on a swing (the picture should include both red frames).", "information": "This installation was create by Gap Filler with the aim of creating more spaces for young people to relax and spend time at in the city.", "note": null, "bonus": null, "points_int": 10 }, "geometry": { "type": "Point", "coordinates": [ 172.64002, -43.52916, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Nga Whāriki Manaaki", "points": "+10 plus bonus points (see below).", "challenge": "Take a photo on a welcome mat", "information": "Ngā Whāriki Manaaki were created by Matapopore, a charitable trust set up by Ngāi Tūāhuriri, a hapū (sub-tribe) of Ngāi Tahu. The project was created to introduce Ngāi Tahu and Ngāi Tūāhurir values into the rebuild of the central city, with each location representing a different value. ", "note": "There are 13 welcome mats total along the Ōtākaro (Avon) River. You will receive a bonus +5 points for each extra mat you take a photo with.", "bonus": "Bonus +5 What do 'Ki Uta' and 'Ki Tai' mean?", "points_int": 10, "bonus_int_1": 5 }, "geometry": { "type": "Point", "coordinates": [ 172.63876, -43.52832, 0.0 ] } },
    { "type": "Feature", "properties": { "name": "Christchurch Changes Frame", "points": "+5", "challenge": "Take a photo of a team member in a frame.", "information": "These frames have been placed as photo opportunities in places of large planned development, allowing passers-by to record and recognise the changes taking place throughout the city.", "note": "Optional, unmarked on map. You will get points for each different location.", "bonus": null, "points_int": 5 }, "geometry": { "type": "Point", "coordinates": [ 172.6363, -43.53039, 0.0 ] } }
    ]
    }
    